### ISSUE TITLE
Priceranges class name not Found 

### ISSUE THREAD

**Issue by Monikatadvi** [aurmil/magento-customize-price-filter#12]
Hi,

Please help to Solve this . I m using your module my site is stop working in product page and admin categories page.

its display error in category page like : 
Fatal error: Class 'Aurmil_CustomizePriceFilter_Block_Adminhtml_Catalog_Category_Helper_Priceranges' not found in C:\xampp\htdocs\backup\lib\Varien\Data\Form\Abstract.php on line 146

and in Log exception file says 
Warning: include(): Failed opening 'Mage\Aurmil\Customizepricefilter\Block\Adminhtml\Catalog\Category\Helper\Priceranges.php' 

Please Help What can I do to resolve quick..

Thanks,
Monika

**Comment by aurmil** [comment]
hello

what's your Magento version?

how did you install the module (manually, modman, ...)?

did you clear all kind of caches (rebuild compilation, clear Magento caches, APC, Memcache, extensions' caches like AOE ClassPathCache, ...)?

**Comment by Monikatadvi** [comment]
Hi,



My Magento version is 1.9.0.1 .

I did  install Manually ..

I am doing all ways by clear cache , compliation , and all .

In error report says :

a:5:{i:0;s:663:"SQLSTATE[42S22]: Column not found: 1054 Unknown column
'FLOOR((ROUND((e.min_price) * 1, 2)) / 1000) + 1' in 'order clause',
query was: SELECT FLOOR((ROUND((e.min_price) * 1, 2)) / 1000) + 1 AS
`range`, COUNT(*) AS `count` FROM `catalog_product_index_price` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON
cat_index.product_id=e.entity_id AND cat_index.store_id=2 AND
cat_index.visibility IN(2, 4) AND cat_index.category_id = '23' WHERE (
e.website_id = '1' ) AND ( e.customer_group_id = 0) AND (e.min_price
IS NOT NULL) GROUP BY FLOOR((ROUND((e.min_price) * 1, 2)) / 1000) + 1
ORDER BY `FLOOR((ROUND((e`.`min_price) * 1, 2)) / 1000) + 1`
ASC";i:1;s:5458:"#0
/home/nyassaba/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110):
Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/nyassaba/public_html/app/code/core/Zend/Db/Statement.php(291):
Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/nyassaba/public_html/lib/Zend/Db/Adapter/Abstract.php(480):
Zend_Db_Statement->execute(Array)
#3 /home/nyassaba/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238):
Zend_Db_Adapter_Abstract->query('SELECT FLOOR((R...', Array)
#4 /home/nyassaba/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428):
Zend_Db_Adapter_Pdo_Abstract->query('SELECT FLOOR((R...', Array)
#5 /home/nyassaba/public_html/lib/Zend/Db/Adapter/Abstract.php(811):
Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Resource/Layer/Filter/Price.php(274):
Zend_Db_Adapter_Abstract->fetchPairs(Object(Varien_Db_Select))
#7 /home/nyassaba/public_html/app/code/community/Aurmil/CustomizePriceFilter/Model/Catalog/Layer/Filter/Price.php(229):
Mage_Catalog_Model_Resource_Layer_Filter_Price->getCount(Object(Aurmil_CustomizePriceFilter_Model_Catalog_Layer_Filter_Price),
1000)
#8 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Layer/Filter/Price.php(115):
Aurmil_CustomizePriceFilter_Model_Catalog_Layer_Filter_Price->getRangeItemCounts(1000)
#9 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Layer/Filter/Price.php(314):
Mage_Catalog_Model_Layer_Filter_Price->getPriceRange()
#10 /home/nyassaba/public_html/app/code/community/Aurmil/CustomizePriceFilter/Model/Catalog/Layer/Filter/Price.php(142):
Mage_Catalog_Model_Layer_Filter_Price->_getItemsData()
#11 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Layer/Filter/Abstract.php(151):
Aurmil_CustomizePriceFilter_Model_Catalog_Layer_Filter_Price->_getItemsData()
#12 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Layer/Filter/Abstract.php(120):
Mage_Catalog_Model_Layer_Filter_Abstract->_initItems()
#13 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Model/Layer/Filter/Abstract.php(109):
Mage_Catalog_Model_Layer_Filter_Abstract->getItems()
#14 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Block/Layer/Filter/Abstract.php(132):
Mage_Catalog_Model_Layer_Filter_Abstract->getItemsCount()
#15 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Block/Layer/View.php(218):
Mage_Catalog_Block_Layer_Filter_Abstract->getItemsCount()
#16 /home/nyassaba/public_html/app/code/core/Mage/Catalog/Block/Layer/View.php(233):
Mage_Catalog_Block_Layer_View->canShowOptions()
#17 /home/nyassaba/public_html/app/design/frontend/ultimo/default/template/catalog/layer/view.phtml(34):
Mage_Catalog_Block_Layer_View->canShowBlock()
#18 /home/nyassaba/public_html/app/code/core/Mage/Core/Block/Template.php(241):
include('/home/nyassaba/...')

Please Give  any idea..



Thanks,
Monika

**Comment by Monikatadvi** [comment]
Hi, 

Please Reply Soon as possible

My site is goes to down

**Comment by aurmil** [comment]
1/ if your site is down and you think this extensions causes it, just disable the extension...
open **app/etc/modules/Aurmil_CustomizePriceFilter.xml** and change 
```xml
<active>true</active>
```
to 
```xml
<active>false</active>
```

then refresh caches

2/ did you test the extension on a dev instance of your site before doing it on the live one?
always test on dev/staging site!

3/ btw, I don't see the link between your first problem (class not found / failed opening file) and the second one (SQL query)

4/ the ORDER clause in the generated SQL query is badly quoted, it should be
```sql
ORDER BY FLOOR((ROUND((e.min_price) * 1, 2)) / 1000) + 1
```
I guess it is done by **app/code/core/Mage/Catalog/Model/Resource/Layer/Filter/Price.php**

6/ please tell me how you configured **System > Configuration > Catalog > Catalog > Layered Navigation**
what are you versions of PHP / MySQL?

5/ I can't help you more now, week end, not at home, no dev tools, can't test, free extension, no paid support
just disable the extension, install it on a dev version of your site, with the same datas as the live site and do some debug, I will try to check this week when I will have some time

**Comment by aurmil** [comment]
can't reproduce bug, never had answer
