### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by micheledalonzo** [aurmil/magento-customize-price-filter#14]
Hi,
I need to uninstall price filter but is seems that setting "false" as ususl is not enough since I receive an error, eve after flushed cache; no compiler.
May you help me?
Thanks in advance
Michele

**Comment by micheledalonzo** [comment]
oh, magento 1.9 ultimo theme

**Comment by aurmil** [comment]
hello,
you should delete the attribute "filter_price_ranges" in the "eav_attribute" table
then re-index "category flat data" index
flush caches again
did you look into logs/reports?
regards

**Comment by micheledalonzo** [comment]
Hi, thanks for your response;
After deleting attribute and reindex we got following error:


2015-05-27T09:24:49+00:00 ERR (3): Warning:
include(Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php):
failed to open stream: No such file or directory  in
/var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:24:49+00:00 ERR (3): Warning: include(): Failed opening
'Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php'
for inclusion
(include_path='/var/www/vhosts/testgalli/httpdocs/app/code/local:/var/www/vhosts/testgalli/httpdocs/app/code/community:/var/www/vhosts/testgalli/httpdocs/app/code/core:/var/www/vhosts/testgalli/httpdocs/lib:.:/usr/share/php:/usr/share/pear')
 in /var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:16+00:00 ERR (3): Warning:
include(Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php):
failed to open stream: No such file or directory  in
/var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:16+00:00 ERR (3): Warning: include(): Failed opening
'Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php'
for inclusion
(include_path='/var/www/vhosts/testgalli/httpdocs/app/code/local:/var/www/vhosts/testgalli/httpdocs/app/code/community:/var/www/vhosts/testgalli/httpdocs/app/code/core:/var/www/vhosts/testgalli/httpdocs/lib:.:/usr/share/php:/usr/share/pear')
 in /var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:21+00:00 ERR (3): Warning:
include(Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php):
failed to open stream: No such file or directory  in
/var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:21+00:00 ERR (3): Warning: include(): Failed opening
'Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php'
for inclusion
(include_path='/var/www/vhosts/testgalli/httpdocs/app/code/local:/var/www/vhosts/testgalli/httpdocs/app/code/community:/var/www/vhosts/testgalli/httpdocs/app/code/core:/var/www/vhosts/testgalli/httpdocs/lib:.:/usr/share/php:/usr/share/pear')
 in /var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:36+00:00 ERR (3): Warning:
include(Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php):
failed to open stream: No such file or directory  in
/var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:36+00:00 ERR (3): Warning: include(): Failed opening
'Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php'
for inclusion
(include_path='/var/www/vhosts/testgalli/httpdocs/app/code/local:/var/www/vhosts/testgalli/httpdocs/app/code/community:/var/www/vhosts/testgalli/httpdocs/app/code/core:/var/www/vhosts/testgalli/httpdocs/lib:.:/usr/share/php:/usr/share/pear')
 in /var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:52+00:00 ERR (3): Warning:
include(Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php):
failed to open stream: No such file or directory  in
/var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94
2015-05-27T09:25:52+00:00 ERR (3): Warning: include(): Failed opening
'Mage/Aurmil/Customizepricefilter/Model/Catalog/Category/Attribute/Backend/Priceranges.php'
for inclusion
(include_path='/var/www/vhosts/testgalli/httpdocs/app/code/local:/var/www/vhosts/testgalli/httpdocs/app/code/community:/var/www/vhosts/testgalli/httpdocs/app/code/core:/var/www/vhosts/testgalli/httpdocs/lib:.:/usr/share/php:/usr/share/pear')
 in /var/www/vhosts/testgalli/httpdocs/lib/Varien/Autoload.php on line 94

Can you help me?
Thankyou in advance
Michele


2015-05-25 21:39 GMT+02:00 Aurélien Millet <notifications@github.com>:

**Comment by aurmil** [comment]
hello

on a Magento 1.9.1.0, I successfully disabled my module:
- set active = false in app/etc/Aurmil_CustomizePriceFilter.xml
- removed "filter_price_ranges" attribute from "eav_attribute" table
- re indexed everything
- flushed caches (APC / OpCache ; Magento ; ...)

do you use Magento compilation? do not forget to run it again each time a class is added/modified/removed

I don't know why, after doing these steps, a file of this module could still be included...

**Comment by aurmil** [comment]
I can confirm the previous steps to disable the module on a 1.9
