### ISSUE TITLE
in FE Price-Filter is not applied (in BE seems all fine)

### ISSUE THREAD

**Issue by HenryLamorski** [aurmil/magento-customize-price-filter#16]
Hey,

in BE all the documented options are available. 
But in FE it seems, the module is ignored. My Price Navigation shows like without your module:
it shows "0-10 €" and "10 and above". 

My Products have a Pricerange like this:

1,20 €
1,75 €
2,30 €
3,53 €
...
10,33 €

What i do so far:

i clean megento caches and rebuild indexes

here my layered navigation block in admin > system > config > catalog:

show Product count: yes
price nav. step calc: manual
default price nav step: 1
maximum number of price intervals: 40
Price Ranges: -2;2-4;4-20
Substract 0.01: no

logs are enabled, all fine, no errors

Magento CE 1.9.1.0
no other Modules
Article/Category Flat Data activated (deactivated same behavior) 

How can i approach a Price Navigation like
0-2 €
2-4 €
4-20 €

Thank you!

**Comment by aurmil** [comment]
hello

FE / BE = EE / CE?
but who's who?

I don't have any EE licence to test my module with

can only help with CE if it's the version that does not work for you

**Comment by aurmil** [comment]
module works fine on CE 1.9, can't test on EE
