### ISSUE TITLE
Provided Layered Navigation Price Ranges are incorrect

### ISSUE THREAD

**Issue by primanegara** [aurmil/magento-customize-price-filter#17]
Thanks before for your free plugin, but i got the problem when put the price range on backend, i'm sure i was put the correct format of price range like this 10-20;20-30;. 

But, I got the problem is (Provided Layered Navigation Price Ranges are incorrect),
can you help me please.. ?

**Comment by aurmil** [comment]
hello
you should not end price ranges with a semi colon
please read again https://github.com/aurmil/magento-customize-price-filter#use-custom-price-ranges
