### ISSUE TITLE
Special Price

### ISSUE THREAD

**Issue by cybricks** [aurmil/magento-customize-price-filter#18]
Hey! Would like the plugin to take into account the special price if available for a product.

**Comment by aurmil** [comment]
hello

can you provide a sample case showing the bug that I could check on my side?
for example with base magento + sample datas

this module is just another way to deal with price filter but does not change the way Magento filters the results so I'm not sure to see where this kind of bug could happen

**Comment by cybricks** [comment]
Hey!

Check this - http://www.pinkshink.com/dev/sarees/cotton.html <http://www.pinkshink.com/dev/sarees/cotton.html>

All products are slashed to INR 1199 but price filter still shows filter 1500-300 cause their original price was INR 2399

Any solution for this ?

Cheers!



-----


 <http://www.cybricks.com/>
Ashwin Haryani
ashwin@cybricks.com <mailto:ashwin@cybricks.com> / 9999917244

CYBRICKS
011-41040440
M-10, 4th Floor, South Extension Part 2
http://www.cybricks.com <http://www.cybricks.com/>
  <https://www.facebook.com/cybricks>  <https://twitter.com/cybricks> <https://www.linkedin.com/company/cybricks>

--------------------------------------------------------------------- 
This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by cybricks** [comment]
Magento Ver 1.9.2.4

Same config for all categories & stores.




Cheers!



-----


 <http://www.cybricks.com/>
Ashwin Haryani
ashwin@cybricks.com <mailto:ashwin@cybricks.com> / 9999917244

CYBRICKS
011-41040440
M-10, 4th Floor, South Extension Part 2
http://www.cybricks.com <http://www.cybricks.com/>
  <https://www.facebook.com/cybricks>  <https://twitter.com/cybricks> <https://www.linkedin.com/company/cybricks>

--------------------------------------------------------------------- 
This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by aurmil** [comment]
OK so please copy/paste here the price ranges you configured
thanks

**Comment by cybricks** [comment]
-1500;1500-3000;3000-4500;4500-

**Comment by cybricks** [comment]
Also check now, i have added special price to as another filter. http://www.pinkshink.com/dev/sarees/cotton.html

**Comment by aurmil** [comment]
OK
I'll have to check how Magento deals with this by default and if this is really of bug in the module or a normal behavior from Magento
can't promise a deadline, as usual... :-/

**Comment by cybricks** [comment]
Sure.. Appreciate the help ..

**Comment by aurmil** [comment]
hi

looking closer to your example, there is something I don't understand:
you say you configured the module like this: "-1500;1500-3000;3000-4500;4500-"
items you show as example prices are: 999 instead of 2,399
and the filter displayed is "₹1,500 and above (25)"
there can't be such a filter with my module and the configuration you set, it should have been configured with "1500-" at the end...

I just tested on a fresh Magento CE 1.9.2.4 + sample data
I checked with the "Sale" category which groups 4 items with special prices
with and without the module, everything works as expected, filters manage special price
so I was not able to reproduce this bug
I'm afraid you will have to test and debug this on your own as I can not do it

regards

**Comment by aurmil** [comment]
were you able to check your config (see first paragraph of my previous post)?
